server:
  port: 8092

jwt:
  secret:
    key: 76397924423F4528482B4D6251655468576D5A7134743777217A25432A46294A

spring:
  datasource:
    password: postgres
    url: jdbc:postgres://localhost:5432/golpi
    username: postgres
  #zona horaria
  jackson:
    time-zone: America/Bogota
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
  application:
    name: golpi