server:
  port: 8092

jwt:
  secret:
    key: 76397924423F4528482B4D6251655468576D5A7134743777217A25432A46294A

spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/golpi
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  #zona horaria
  jackson:
    date-format: yyyy-MM-dd
    time-zone: America/Bogota
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
  application:
    name: golpi
logging:
  level:
    org.springframework.web: DEBUG
