server:
  port: 8092

jwt:
  secret:
    key: 76397924423F4528482B4D6251655468576D5A7134743777217A25432A46294A

spring:

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  #zona horaria
  jackson:
    date-format: yyyy-MM-dd
    time-zone: America/Bogota
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
  application:
    name: golpi
logging:
  level:
    org.springframework.web: DEBUG
twilio:
  accountSid: AC4e390862fc25a97f9e5842d2a817463f
  authToken: af1cc89d7e8a359ee6b1d93eac1fab21
